version: "3"
services:
  php:
    build: ./php
    volumes:
      - ~/Documents/www/phpwww:/var/www
  nginx:
    image: nginx:alpine 
    ports:
      - 80:80
    volumes:  
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ~/Documents/www/phpwww:/var/www
  mysql: # 添加 mysql 服务
    image: mysql:5.6
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - MYSQL_ROOT_PASSWORD=123455 # 设置 root 用户密码
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置编码
  redis:
    image: redis:5.0.5-alpine 
    ports:
      - 63799:6379
